config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new', as: :new_task

  post 'tasks', to: 'tasks#create', as: :tasks

  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit

  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy', as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to root_path
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to root_path
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :Title %>
  <%= f.text_field :title %>

  <%= f.label :Details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="box">
        <h1>Tristan's boring tasks 😴</h1>
        <p class="button inline"><%= link_to 'Home', root_path %></p>
        <p class="button inline"><%= link_to 'Add new task', new_task_path %></p>
        <br><br>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :Title %>
  <%= f.text_field :title %>

  <br><br>

  <%= f.label :Details %>
  <%= f.text_field :details %>

  <br><br>

  <% unless task.new_record? %>
    <%= f.label :Mark_as_complete? %>
    <%= f.check_box :completed %>
  <% end %>

  <br><br>

  <%= f.submit %>

<% end %>

app/views/tasks/edit.html.erb
<h3>Edit task</h3>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
  <% @tasks.each do |task| %>
    <br>
    <%= check_box("Completed?", task.completed, {checked: task.completed}) %>
    <%= link_to task.title, task_path(task.id) %>
    <%= link_to "🗑", delete_path(task),
    method: :delete,
    data: { confirm: "Delete '#{task.title}?" }%>
  <% end %>

app/views/tasks/new.html.erb
<h3>Add new task</h3>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h3><%= @task.title %></h3>

<p class="callout"><%= @task.details %></p>

<p class="callout"><%= @task.completed? ? "✅ Task complete!" : " ❌ Task not complete!" %></p>

<p class="button"><%= link_to "Edit task", edit_path(@task.id) %> </p>